//! توليد قوالب HTML من EntityConfig
//!
//! يستخدم replace() بدلاً من format!() لتجنب تعارض
//! { و } مع صياغة Askama ({% %} و {{ }}).

use novax_core::{EntityConfig, FieldConfig, FieldType, ProjectConfig};

fn fill(template: &str, vars: &[(&str, &str)]) -> String {
    let mut result = template.to_string();
    for (key, value) in vars {
        result = result.replace(key, value);
    }
    result
}

/// توليد قالب list
pub fn generate_list_template(entity: &EntityConfig) -> String {
    let entity_snake = novax_core::to_snake_case(&entity.name);
    let route_prefix = entity.route_prefix();
    let display_name_plural = &entity.display_name_plural;
    let display_name = &entity.display_name;

    let table_headers: String = entity.list_fields().iter()
        .map(|f| format!("        <th>{}</th>", f.label))
        .collect::<Vec<_>>()
        .join("\n");

    let template = r##"<!-- AUTO-GENERATED by Novax Engine -->
{% extends "layout" %}

{% block content %}
<div class="container">
  <div class="page-header">
    <h1>__PLURAL__</h1>
    <a href="/__PREFIX__/new" class="btn btn-primary" hx-target="#main">
      + إضافة جديدة
    </a>
  </div>

  {% if items.is_empty() %}
    <div class="empty-state">
      <p>لا توجد __PLURAL__ بعد.</p>
      <a href="/__PREFIX__/new" class="btn btn-primary" style="margin-top: 16px;">+ إضافة أول __SINGULAR__</a>
    </div>
  {% else %}
    <table class="table">
      <thead>
        <tr>
__HEADERS__
          <th>إجراءات</th>
        </tr>
      </thead>
      <tbody id="__SNAKE__-table"
             hx-target="this"
             hx-swap="innerHTML">
        {% for item in items %}
          {% include "partials/__SNAKE___row" %}
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
</div>
{% endblock %}
"##;

    fill(template, &[
        ("__PLURAL__", display_name_plural),
        ("__SINGULAR__", display_name),
        ("__PREFIX__", &route_prefix),
        ("__SNAKE__", &entity_snake),
        ("__HEADERS__", &table_headers),
    ])
}

/// توليد قالب form
pub fn generate_form_template(entity: &EntityConfig) -> String {
    let entity_snake = novax_core::to_snake_case(&entity.name);
    let route_prefix = entity.route_prefix();
    let display_name = &entity.display_name;

    let form_fields: String = entity.form_fields().iter()
        .map(|f| format_form_field(f))
        .collect::<Vec<_>>()
        .join("\n");

    let template = r##"<!-- AUTO-GENERATED by Novax Engine -->
{% extends "layout" %}

{% block content %}
<div class="container" style="max-width: 600px;">
  <div class="page-header">
    <h1>__NAME__ جديد</h1>
  </div>

  <div class="card">
    <form method="POST"
          action="/__PREFIX__"
          hx-post="/__PREFIX__"
          hx-target="#__SNAKE__-table tbody"
          hx-swap="afterbegin"
          hx-on::after-request="this.reset()">
__FIELDS__
      <button type="submit" class="btn btn-primary">حفظ</button>
      <a href="/__PREFIX__" class="btn btn-secondary">إلغاء</a>
    </form>
  </div>
</div>
{% endblock %}
"##;

    fill(template, &[
        ("__NAME__", display_name),
        ("__PREFIX__", &route_prefix),
        ("__SNAKE__", &entity_snake),
        ("__FIELDS__", &form_fields),
    ])
}

fn format_form_field(f: &FieldConfig) -> String {
    let input_type = f.field_type.html_input_type();
    let label = &f.label;
    let name = &f.name;
    let required = if f.required { "required" } else { "" };

    if input_type == "textarea" {
        format!(
            r#"      <div class="form-group">
        <label for="{name}">{label}</label>
        <textarea name="{name}" id="{name}" {required} rows="3"></textarea>
      </div>"#,
            name = name, label = label, required = required,
        )
    } else if input_type == "checkbox" {
        format!(
            r#"      <div class="form-group">
        <label>
          <input type="checkbox" name="{name}" id="{name}" value="true" {checked}>
          {label}
        </label>
      </div>"#,
            name = name, label = label,
            checked = if f.default_value.as_deref() == Some("true") { "checked" } else { "" },
        )
    } else {
        format!(
            r#"      <div class="form-group">
        <label for="{name}">{label}</label>
        <input type="{input_type}" name="{name}" id="{name}" {required}>
      </div>"#,
            input_type = input_type, name = name, label = label, required = required,
        )
    }
}

/// توليد قالب detail
pub fn generate_detail_template(entity: &EntityConfig) -> String {
    let entity_snake = novax_core::to_snake_case(&entity.name);
    let route_prefix = entity.route_prefix();
    let display_name = &entity.display_name;

    let detail_rows: String = entity.fields.iter()
        .filter(|f| f.display_in_detail)
        .map(|f| {
            let value_expr = format_field_display(f, &entity_snake);
            format!(
                "      <tr><td><strong>{}</strong></td><td>{}</td></tr>",
                f.label, value_expr
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let template = r##"<!-- AUTO-GENERATED by Novax Engine -->
{% extends "layout" %}

{% block content %}
<div class="container" style="max-width: 700px;">
  <div class="page-header">
    <h1>__NAME__</h1>
    <a href="/__PREFIX__" class="btn btn-secondary">← العودة للقائمة</a>
  </div>

  <div class="card">
    <table class="table">
      <tbody>
__ROWS__
      </tbody>
    </table>
  </div>
</div>
{% endblock %}
"##;

    fill(template, &[
        ("__NAME__", display_name),
        ("__PREFIX__", &route_prefix),
        ("__ROWS__", &detail_rows),
    ])
}

/// توليد قالب partial row (HTMX)
pub fn generate_row_partial(entity: &EntityConfig) -> String {
    let entity_snake = novax_core::to_snake_case(&entity.name);
    let route_prefix = entity.route_prefix();

    let cells: String = entity.list_fields().iter()
        .map(|f| format_row_cell(f, &entity_snake))
        .collect::<Vec<_>>()
        .join("\n        ");

    let template = r##"<!-- HTMX partial: single row -->
<tr id="__SNAKE__-{{ item.id }}">
        __CELLS__
        <td class="actions">
          <a href="/__PREFIX__/{{ item.id }}" class="btn btn-secondary btn-sm">عرض</a>
          <button hx-delete="/__PREFIX__/{{ item.id }}/delete"
                  hx-target="closest tr"
                  hx-swap="outerHTML"
                  hx-confirm="هل أنت متأكد؟"
                  class="btn btn-danger btn-sm">
            حذف
          </button>
        </td>
      </tr>"##;

    fill(template, &[
        ("__SNAKE__", &entity_snake),
        ("__PREFIX__", &route_prefix),
        ("__CELLS__", &cells),
    ])
}

/// توليد قالب layout الأساسي
pub fn generate_layout_template(project: &ProjectConfig) -> String {
    let nav_links: String = project.entities.iter()
        .map(|e| {
            format!(
                r#"    <a href="/{prefix}">{icon} {name}</a>"#,
                prefix = e.route_prefix(),
                icon = e.icon,
                name = e.display_name_plural,
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let dir = &project.theme.direction;
    let lang = &project.theme.lang;

    let template = r##"<!DOCTYPE html>
<html lang="__LANG__" dir="__DIR__">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{{ project_name }}{% endblock %}</title>
  <link rel="stylesheet" href="/static/styles.css">
  <script src="https://unpkg.com/htmx.org@1.9.10"></script>
  <script defer src="https://unpkg.com/alpinejs@3.x.x"></script>
</head>
<body>
  <div class="container">
    <nav class="nav">
__NAV__
    </nav>
    <div id="main">
      {% block content %}{% endblock %}
    </div>
  </div>
</body>
</html>"##;

    fill(template, &[
        ("__LANG__", lang),
        ("__DIR__", dir),
        ("__NAV__", &nav_links),
    ])
}

fn format_row_cell(f: &FieldConfig, entity_snake: &str) -> String {
    let value = match f.field_type {
        FieldType::Boolean => {
            format!("{{% if {snake}.{name} %}}<span class=\"badge badge-success\">✓</span>{{% else %}}<span class=\"badge badge-danger\">✗</span>{{% endif %}}",
                name = f.name, snake = entity_snake)
        }
        FieldType::Timestamp => {
            format!("{{{{ {snake}.{name}.format(\"%Y-%m-%d %H:%M\") }}}}", name = f.name, snake = entity_snake)
        }
        _ => format!("{{{{ {snake}.{name} }}}}", name = f.name, snake = entity_snake),
    };
    format!("        <td>{}</td>", value)
}

fn format_field_display(f: &FieldConfig, entity_snake: &str) -> String {
    match f.field_type {
        FieldType::Boolean => {
            format!("{{% if {snake}.{name} %}}<span class=\"badge badge-success\">نعم</span>{{% else %}}<span class=\"badge badge-danger\">لا</span>{{% endif %}}",
                name = f.name, snake = entity_snake)
        }
        FieldType::Timestamp => {
            format!("{{{{ {snake}.{name}.format(\"%Y-%m-%d %H:%M:%S\") }}}}", name = f.name, snake = entity_snake)
        }
        _ => format!("{{{{ {snake}.{name} }}}}", name = f.name, snake = entity_snake),
    }
}
