//! توليد OpenAPI/Swagger specification من ProjectConfig
//!
//! يُولّد JSON يتوافق مع OpenAPI 3.0.3 لكل كيان في المشروع.

use novax_core::{EntityConfig, FieldConfig, FieldType, ProjectConfig};
use serde_json::{json, Value, Map};

/// توليد OpenAPI spec كامل لمشروع
pub fn generate_openapi_spec(project: &ProjectConfig) -> Value {
    let mut paths = Map::new();
    let mut schemas = Map::new();

    for entity in &project.entities {
        // أضف المسارات
        add_entity_paths(&mut paths, entity);
        // أضف الـ schemas
        add_entity_schema(&mut schemas, entity);
    }

    json!({
        "openapi": "3.0.3",
        "info": {
            "title": project.display_name,
            "description": project.description.as_deref().unwrap_or("Generated by Novax Engine"),
            "version": "1.0.0"
        },
        "servers": [
            { "url": "http://localhost:3000", "description": "Local development" }
        ],
        "paths": paths,
        "components": {
            "schemas": schemas
        }
    })
}

fn add_entity_paths(paths: &mut Map<String, Value>, entity: &EntityConfig) {
    let prefix = format!("/{}", entity.route_prefix());
    let struct_name = entity.struct_name();

    // GET /{prefix} — list
    paths.insert(prefix.clone(), json!({
        "get": {
            "summary": format!("List all {}", entity.display_name_plural),
            "tags": [struct_name],
            "parameters": [
                {
                    "name": "page",
                    "in": "query",
                    "schema": { "type": "integer", "default": 1 }
                },
                {
                    "name": "per_page",
                    "in": "query",
                    "schema": { "type": "integer", "default": 20, "maximum": 100 }
                },
                {
                    "name": "search",
                    "in": "query",
                    "schema": { "type": "string" },
                    "description": "Search in searchable fields"
                }
            ],
            "responses": {
                "200": {
                    "description": "List of items",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "items": {
                                        "type": "array",
                                        "items": { "$ref": format!("#/components/schemas/{}", struct_name) }
                                    },
                                    "total": { "type": "integer" },
                                    "page": { "type": "integer" },
                                    "per_page": { "type": "integer" }
                                }
                            }
                        }
                    }
                }
            }
        },
        "post": {
            "summary": format!("Create a new {}", entity.display_name),
            "tags": [struct_name],
            "requestBody": {
                "content": {
                    "application/json": {
                        "schema": { "$ref": format!("#/components/schemas/Create{}", struct_name) }
                    }
                }
            },
            "responses": {
                "201": {
                    "description": "Created",
                    "content": {
                        "application/json": {
                            "schema": { "$ref": format!("#/components/schemas/{}", struct_name) }
                        }
                    }
                }
            }
        }
    }));

    // GET /{prefix}/:id — get by ID
    paths.insert(format!("{}/{{id}}", prefix), json!({
        "get": {
            "summary": format!("Get a single {}", entity.display_name),
            "tags": [struct_name],
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "schema": { "type": "string", "format": "uuid" }
                }
            ],
            "responses": {
                "200": {
                    "description": "Single item",
                    "content": {
                        "application/json": {
                            "schema": { "$ref": format!("#/components/schemas/{}", struct_name) }
                        }
                    }
                },
                "404": { "description": "Not found" }
            }
        },
        "patch": {
            "summary": format!("Update a {}", entity.display_name),
            "tags": [struct_name],
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "schema": { "type": "string", "format": "uuid" }
                }
            ],
            "requestBody": {
                "content": {
                    "application/json": {
                        "schema": { "$ref": format!("#/components/schemas/Update{}", struct_name) }
                    }
                }
            },
            "responses": {
                "200": {
                    "description": "Updated",
                    "content": {
                        "application/json": {
                            "schema": { "$ref": format!("#/components/schemas/{}", struct_name) }
                        }
                    }
                }
            }
        },
        "delete": {
            "summary": format!("Delete a {}", entity.display_name),
            "tags": [struct_name],
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "schema": { "type": "string", "format": "uuid" }
                }
            ],
            "responses": {
                "204": { "description": "Deleted" }
            }
        }
    }));
}

fn add_entity_schema(schemas: &mut Map<String, Value>, entity: &EntityConfig) {
    let struct_name = entity.struct_name();

    // Main schema
    let mut properties = Map::new();
    for field in &entity.fields {
        properties.insert(field.name.clone(), field_to_schema(field));
    }
    schemas.insert(struct_name.clone(), json!({
        "type": "object",
        "properties": properties,
        "required": entity.fields.iter()
            .filter(|f| f.required)
            .map(|f| f.name.clone())
            .collect::<Vec<_>>()
    }));

    // Create schema (no auto-generated fields)
    let mut create_props = Map::new();
    for field in entity.fields.iter().filter(|f| !f.auto_generate && f.display_in_form) {
        create_props.insert(field.name.clone(), field_to_schema(field));
    }
    schemas.insert(format!("Create{}", struct_name), json!({
        "type": "object",
        "properties": create_props,
        "required": entity.fields.iter()
            .filter(|f| !f.auto_generate && f.display_in_form && f.required)
            .map(|f| f.name.clone())
            .collect::<Vec<_>>()
    }));

    // Update schema (all optional)
    let mut update_props = Map::new();
    for field in entity.fields.iter().filter(|f| !f.auto_generate && f.display_in_form) {
        let mut schema = field_to_schema(field);
        if let Value::Object(ref mut map) = schema {
            map.insert("nullable".to_string(), json!(true));
        }
        update_props.insert(field.name.clone(), schema);
    }
    schemas.insert(format!("Update{}", struct_name), json!({
        "type": "object",
        "properties": update_props
    }));
}

fn field_to_schema(f: &FieldConfig) -> Value {
    match f.field_type {
        FieldType::Uuid => json!({ "type": "string", "format": "uuid", "description": f.label }),
        FieldType::String => json!({ "type": "string", "description": f.label, "maxLength": f.max_length.unwrap_or(255) }),
        FieldType::Text => json!({ "type": "string", "description": f.label }),
        FieldType::Integer => json!({ "type": "integer", "format": "int64", "description": f.label }),
        FieldType::Decimal => json!({ "type": "number", "format": "double", "description": f.label }),
        FieldType::Boolean => json!({ "type": "boolean", "description": f.label }),
        FieldType::Timestamp => json!({ "type": "string", "format": "date-time", "description": f.label }),
        FieldType::Date => json!({ "type": "string", "format": "date", "description": f.label }),
        FieldType::Json => json!({ "type": "object", "description": f.label }),
        FieldType::Reference => json!({ "type": "string", "format": "uuid", "description": format!("{} (FK to {})", f.label, f.references.as_deref().unwrap_or("unknown")) }),
    }
}

/// توليد صفحة Swagger UI HTML (مدمجة، بدون خادم خارجي)
pub fn generate_swagger_ui(spec: &Value) -> String {
    let spec_json = serde_json::to_string_pretty(spec).unwrap_or_default();
    format!(
        r##"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>API Inspector — Novax</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5.11.0/swagger-ui.css">
  <style>
    body {{ margin: 0; }}
    .swagger-ui .topbar {{ display: none; }}
  </style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5.11.0/swagger-ui-bundle.js"></script>
  <script>
    window.onload = function() {{
      const spec = {spec};
      SwaggerUIBundle({{
        spec: spec,
        dom_id: '#swagger-ui',
        presets: [SwaggerUIBundle.presets.apis],
        layout: 'BaseLayout',
      }});
    }};
  </script>
</body>
</html>"##,
        spec = spec_json,
    )
}
