//! توليد كود Rust من EntityConfig
//! يستخدم replace() بدلاً من format!() لتجنب تعارض { و } مع صياغة Rust.

use novax_core::{EntityConfig, ProjectConfig};

fn fill(template: &str, vars: &[(&str, &str)]) -> String {
    let mut result = template.to_string();
    for (key, value) in vars {
        result = result.replace(key, value);
    }
    result
}

/// توليد ملف models/{entity}.rs
pub fn generate_model(entity: &EntityConfig) -> String {
    let struct_name = entity.struct_name();
    let display_name = &entity.display_name;

    let fields_decls: String = entity.fields.iter()
        .map(|f| format_field_decl(f))
        .collect::<Vec<_>>()
        .join("\n    ");

    let create_fields: String = entity.fields.iter()
        .filter(|f| !f.auto_generate && f.display_in_form)
        .map(|f| format!("    pub {}: {}", f.name, field_rust_type(f)))
        .collect::<Vec<_>>()
        .join("\n");

    let update_fields: String = entity.fields.iter()
        .filter(|f| !f.auto_generate && f.display_in_form)
        .map(|f| format!("    pub {}: Option<{}>", f.name, f.field_type.rust_type()))
        .collect::<Vec<_>>()
        .join("\n");

    let template = r##"//! __NAME__ model — auto-generated by Novax Engine
//! Do not edit manually; re-export from Novax to regenerate.

use sqlx::FromRow;
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, FromRow, Serialize, Deserialize)]
pub struct __STRUCT__ {
__FIELDS__
}

#[derive(Debug, Deserialize)]
pub struct Create__STRUCT__ {
__CREATE_FIELDS__
}

#[derive(Debug, Deserialize)]
pub struct Update__STRUCT__ {
__UPDATE_FIELDS__
}
"##;

    fill(template, &[
        ("__NAME__", display_name),
        ("__STRUCT__", &struct_name),
        ("__FIELDS__", &fields_decls),
        ("__CREATE_FIELDS__", if create_fields.is_empty() { "// no input fields" } else { &create_fields }),
        ("__UPDATE_FIELDS__", if update_fields.is_empty() { "// no updateable fields" } else { &update_fields }),
    ])
}

fn format_field_decl(f: &novax_core::FieldConfig) -> String {
    let type_str = if f.nullable && !f.required {
        format!("Option<{}>", f.field_type.rust_type())
    } else {
        f.field_type.rust_type().to_string()
    };
    format!("    pub {}: {}", f.name, type_str)
}

fn field_rust_type(f: &novax_core::FieldConfig) -> String {
    if f.nullable && !f.required {
        format!("Option<{}>", f.field_type.rust_type())
    } else {
        f.field_type.rust_type().to_string()
    }
}

/// توليد ملف routes/{entity}.rs
pub fn generate_routes(entity: &EntityConfig) -> String {
    let struct_name = entity.struct_name();
    let table = entity.table();
    let route_prefix = entity.route_prefix();
    let display_name = &entity.display_name;
    let display_name_plural = &entity.display_name_plural;
    let entity_snake = novax_core::to_snake_case(&entity.name);

    let select_columns: String = entity.fields.iter()
        .map(|f| f.name.clone())
        .collect::<Vec<_>>()
        .join(", ");

    let insert_columns: String = entity.fields.iter()
        .filter(|f| !f.auto_generate && f.display_in_form)
        .map(|f| f.name.clone())
        .collect::<Vec<_>>()
        .join(", ");

    let insert_placeholders: String = entity.fields.iter()
        .filter(|f| !f.auto_generate && f.display_in_form)
        .enumerate()
        .map(|(i, _)| format!("${}", i + 1))
        .collect::<Vec<_>>()
        .join(", ");

    let insert_binds: String = entity.fields.iter()
        .filter(|f| !f.auto_generate && f.display_in_form)
        .map(|f| format!(".bind(&form.{})", f.name))
        .collect::<Vec<_>>()
        .join("\n    ");

    let template = r##"//! Routes for __NAME__ — auto-generated by Novax Engine
//! Uses HTMX for partial page updates.

use axum::{
    extract::{Path, State},
    response::Html,
    routing::{get, post, delete},
    Router, Form,
    http::StatusCode,
};
use uuid::Uuid;

use crate::models::__SNAKE__::{__STRUCT__, Create__STRUCT__, Update__STRUCT__};
use crate::AppState;

pub fn routes() -> Router<AppState> {
    Router::new()
        .route("/__PREFIX__", get(list___SNAKE__).post(create___SNAKE__))
        .route("/__PREFIX__/new", get(new___SNAKE___form))
        .route("/__PREFIX__/:id", get(show___SNAKE__))
        .route("/__PREFIX__/:id/delete", delete(delete___SNAKE__))
}

/// GET /__PREFIX__ — list __PLURAL__ (SSR)
pub async fn list___SNAKE__(
    State(state): State<AppState>,
) -> Html<String> {
    let items: Vec<__STRUCT__> = sqlx::query_as(
        "SELECT __SELECT__ FROM __TABLE__ ORDER BY created_at DESC LIMIT 50"
    )
    .fetch_all(&state.db)
    .await
    .unwrap_or_default();

    crate::templates::render___SNAKE___list(&items)
}

/// GET /__PREFIX__/new — create form
pub async fn new___SNAKE___form() -> Html<String> {
    crate::templates::render___SNAKE___form(None)
}

/// POST /__PREFIX__ — create + return HTMX partial
pub async fn create___SNAKE__(
    State(state): State<AppState>,
    Form(form): Form<Create__STRUCT__>,
) -> Html<String> {
    let item: __STRUCT__ = sqlx::query_as(
        "INSERT INTO __TABLE__ (__INSERT_COLS__) VALUES (__INSERT_PH__) RETURNING __SELECT__",
    )
    __INSERT_BINDS__
    .fetch_one(&state.db)
    .await
    .unwrap();

    crate::templates::render___SNAKE___row(&item)
}

/// GET /__PREFIX__/:id — detail (SSR)
pub async fn show___SNAKE__(
    State(state): State<AppState>,
    Path(id): Path<Uuid>,
) -> Html<String> {
    let item: __STRUCT__ = sqlx::query_as(
        "SELECT __SELECT__ FROM __TABLE__ WHERE id = $1"
    )
    .bind(id)
    .fetch_one(&state.db)
    .await
    .unwrap();

    crate::templates::render___SNAKE___detail(&item)
}

/// DELETE /__PREFIX__/:id/delete — delete + return OK (HTMX removes row)
pub async fn delete___SNAKE__(
    State(state): State<AppState>,
    Path(id): Path<Uuid>,
) -> StatusCode {
    sqlx::query("DELETE FROM __TABLE__ WHERE id = $1")
        .bind(id)
        .execute(&state.db)
        .await
        .ok();
    StatusCode::OK
}
"##;

    fill(template, &[
        ("__NAME__", display_name),
        ("__PLURAL__", display_name_plural),
        ("__STRUCT__", &struct_name),
        ("__SNAKE__", &entity_snake),
        ("__PREFIX__", &route_prefix),
        ("__TABLE__", &table),
        ("__SELECT__", &select_columns),
        ("__INSERT_COLS__", &insert_columns),
        ("__INSERT_PH__", &insert_placeholders),
        ("__INSERT_BINDS__", &insert_binds),
    ])
}

/// توليد main.rs
pub fn generate_main(project: &ProjectConfig) -> String {
    let entity_modules: String = project.entities.iter()
        .map(|e| format!("    pub mod {};", novax_core::to_snake_case(&e.name)))
        .collect::<Vec<_>>()
        .join("\n");

    let route_registrations: String = project.entities.iter()
        .map(|e| format!(
            "        .nest(\"/{}\", {}::routes())",
            e.route_prefix(),
            novax_core::to_snake_case(&e.name)
        ))
        .collect::<Vec<_>>()
        .join("\n");

    let project_name = &project.name;

    let template = r##"//! __PROJECT__ — generated by Novax Engine
//! Standalone project (zero Novax dependency).

mod config;
mod db;
mod models {
__ENTITIES__
}
mod routes {
__ENTITIES__
}
mod templates;

use axum::Router;
use tokio::net::TcpListener;

#[derive(Clone)]
pub struct AppState {
    pub db: sqlx::PgPool,
}

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();
    let config = config::Config::from_env();
    let db = db::init_pool(&config.database_url).await;
    sqlx::migrate!("./migrations").run(&db).await.expect("migrations failed");
    let state = AppState { db };
    let app = Router::new()
__ROUTES__
        .with_state(state);
    let listener = TcpListener::bind(&config.bind_addr).await.unwrap();
    tracing::info!("listening on http://{}", config.bind_addr);
    axum::serve(listener, app).await.unwrap();
}
"##;

    fill(template, &[
        ("__PROJECT__", project_name),
        ("__ENTITIES__", &entity_modules),
        ("__ROUTES__", &route_registrations),
    ])
}

/// توليد config.rs
pub fn generate_config(project: &ProjectConfig) -> String {
    let db_name = project.dir_name();
    let template = r##"//! App configuration — read from environment

pub struct Config {
    pub database_url: String,
    pub bind_addr: String,
}

impl Config {
    pub fn from_env() -> Self {
        Self {
            database_url: std::env::var("DATABASE_URL")
                .unwrap_or_else(|_| "postgres://localhost/__DB__".to_string()),
            bind_addr: std::env::var("BIND_ADDR")
                .unwrap_or_else(|_| "0.0.0.0:3000".to_string()),
        }
    }
}
"##;

    fill(template, &[("__DB__", &db_name)])
}

/// توليد db.rs
pub fn generate_db() -> String {
    r##"//! PostgreSQL pool initialization

use sqlx::postgres::PgPoolOptions;

pub async fn init_pool(url: &str) -> sqlx::PgPool {
    PgPoolOptions::new()
        .max_connections(10)
        .connect(url)
        .await
        .expect("Failed to connect to PostgreSQL")
}
"##.to_string()
}

/// توليد Cargo.toml
pub fn generate_cargo_toml(project: &ProjectConfig) -> String {
    let project_name = project.dir_name();

    let template = r##"[package]
name = "__NAME__"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "postgres", "uuid", "chrono", "macros", "migrate"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"
"##;

    fill(template, &[("__NAME__", &project_name)])
}
