//! إعدادات المظهر (Theme)
//!
//! تُترجم إلى ملف CSS مع CSS Variables عند التصدير.
//! المستخدم يختار الألوان والخطوط من واجهة Novax،
//! والـ compiler يولّد styles.css تلقائيًا.

use serde::{Deserialize, Serialize};

/// إعدادات المظهر
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThemeConfig {
    /// اللون الأساسي (أزرار، روابط)
    #[serde(default = "default_primary")]
    pub primary_color: String,

    /// لون الخلفية
    #[serde(default = "default_bg")]
    pub bg_color: String,

    /// لون النص
    #[serde(default = "default_text")]
    pub text_color: String,

    /// لون البطاقات/الأسطح
    #[serde(default = "default_surface")]
    pub surface_color: String,

    /// لون الحدود
    #[serde(default = "default_border")]
    pub border_color: String,

    /// لون النجاح
    #[serde(default = "default_success")]
    pub success_color: String,

    /// لون الخطر
    #[serde(default = "default_danger")]
    pub danger_color: String,

    /// عائلة الخط
    #[serde(default = "default_font")]
    pub font_family: String,

    /// نصف قطر الزاوية
    #[serde(default = "default_radius")]
    pub border_radius: String,

    /// الاتجاه (rtl للعربي، ltr للإنجليزي)
    #[serde(default = "default_dir")]
    pub direction: String,

    /// اللغة
    #[serde(default = "default_lang")]
    pub lang: String,
}

fn default_primary() -> String { "#c79a3a".to_string() }
fn default_bg() -> String { "#0f0f10".to_string() }
fn default_text() -> String { "#f0f0f2".to_string() }
fn default_surface() -> String { "#1a1a1c".to_string() }
fn default_border() -> String { "#2a2a2d".to_string() }
fn default_success() -> String { "#518f66".to_string() }
fn default_danger() -> String { "#aa524a".to_string() }
fn default_font() -> String { "system-ui, -apple-system, 'Segoe UI', sans-serif".to_string() }
fn default_radius() -> String { "8px".to_string() }
fn default_dir() -> String { "rtl".to_string() }
fn default_lang() -> String { "ar".to_string() }

impl Default for ThemeConfig {
    fn default() -> Self {
        Self {
            primary_color: default_primary(),
            bg_color: default_bg(),
            text_color: default_text(),
            surface_color: default_surface(),
            border_color: default_border(),
            success_color: default_success(),
            danger_color: default_danger(),
            font_family: default_font(),
            border_radius: default_radius(),
            direction: default_dir(),
            lang: default_lang(),
        }
    }
}

impl ThemeConfig {
    /// توليد ملف CSS كامل من الإعدادات
    pub fn to_css(&self) -> String {
        format!(
            r#"/* Auto-generated by Novax Engine from theme configuration */
:root {{
  --color-primary: {primary};
  --color-bg: {bg};
  --color-text: {text};
  --color-surface: {surface};
  --color-border: {border};
  --color-success: {success};
  --color-danger: {danger};
  --font-family: {font};
  --radius: {radius};
  --dir: {dir};
}}

* {{ margin: 0; padding: 0; box-sizing: border-box; }}

body {{
  background: var(--color-bg);
  color: var(--color-text);
  font-family: var(--font-family);
  direction: var(--dir);
  min-height: 100vh;
  line-height: 1.6;
}}

a {{ color: var(--color-primary); text-decoration: none; }}
a:hover {{ text-decoration: underline; }}

.container {{
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 24px;
}}

.page-header {{
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 24px;
  padding: 16px 0;
}}

.page-header h1 {{
  font-size: 24px;
  font-weight: 700;
}}

.btn {{
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 10px 20px;
  border-radius: var(--radius);
  font-size: 14px;
  font-weight: 600;
  border: none;
  cursor: pointer;
  transition: all 0.2s;
  font-family: inherit;
}}

.btn-primary {{
  background: var(--color-primary);
  color: var(--color-bg);
}}

.btn-primary:hover {{ opacity: 0.9; }}

.btn-secondary {{
  background: var(--color-surface);
  color: var(--color-text);
  border: 1px solid var(--color-border);
}}

.btn-danger {{
  background: var(--color-danger);
  color: white;
}}

.btn-sm {{ padding: 6px 12px; font-size: 12px; }}

.table {{
  width: 100%;
  border-collapse: collapse;
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  overflow: hidden;
}}

.table th {{
  text-align: {th_align};
  padding: 12px 16px;
  font-size: 12px;
  color: var(--color-text);
  opacity: 0.6;
  font-weight: 500;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  border-bottom: 1px solid var(--color-border);
  background: var(--color-surface);
}}

.table td {{
  padding: 14px 16px;
  border-bottom: 1px solid var(--color-border);
  font-size: 14px;
}}

.table tr:hover {{ background: var(--color-border); opacity: 0.5; }}

.card {{
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  padding: 24px;
  margin-bottom: 16px;
}}

.form-group {{
  margin-bottom: 18px;
}}

.form-group label {{
  display: block;
  font-size: 13px;
  margin-bottom: 6px;
  opacity: 0.8;
}}

.form-group input,
.form-group textarea,
.form-group select {{
  width: 100%;
  padding: 10px 14px;
  background: var(--color-bg);
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  color: var(--color-text);
  font-size: 14px;
  font-family: inherit;
}}

.form-group input:focus,
.form-group textarea:focus,
.form-group select:focus {{
  outline: none;
  border-color: var(--color-primary);
}}

.badge {{
  display: inline-flex;
  padding: 4px 10px;
  border-radius: 12px;
  font-size: 11px;
  font-weight: 600;
}}

.badge-success {{
  background: rgba(81, 143, 102, 0.2);
  color: var(--color-success);
}}

.badge-danger {{
  background: rgba(170, 82, 74, 0.2);
  color: var(--color-danger);
}}

.alert {{
  padding: 12px 16px;
  border-radius: var(--radius);
  margin-bottom: 18px;
  font-size: 14px;
}}

.alert-success {{
  background: rgba(81, 143, 102, 0.15);
  border: 1px solid var(--color-success);
  color: var(--color-success);
}}

.alert-danger {{
  background: rgba(170, 82, 74, 0.15);
  border: 1px solid var(--color-danger);
  color: var(--color-danger);
}}

.nav {{
  display: flex;
  gap: 8px;
  padding: 16px 0;
  border-bottom: 1px solid var(--color-border);
  margin-bottom: 24px;
}}

.nav a {{
  padding: 8px 16px;
  border-radius: var(--radius);
  color: var(--color-text);
  opacity: 0.7;
}}

.nav a:hover {{
  background: var(--color-surface);
  opacity: 1;
  text-decoration: none;
}}

.actions {{
  display: flex;
  gap: 8px;
}}

.empty-state {{
  text-align: center;
  padding: 48px 24px;
  opacity: 0.5;
}}
"#,
            primary = self.primary_color,
            bg = self.bg_color,
            text = self.text_color,
            surface = self.surface_color,
            border = self.border_color,
            success = self.success_color,
            danger = self.danger_color,
            font = self.font_family,
            radius = self.border_radius,
            dir = self.direction,
            th_align = if self.direction == "rtl" { "right" } else { "left" },
        )
    }
}
